name: Upload Files to S3

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    name: Upload to AWS S3
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Change this to your desired AWS region

      # Step 3: Upload files to S3 while maintaining folder structure
      - name: Upload files to S3
        run: |
          aws s3 sync . s3://config_files/fhir/ \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "*.yml" \
            --exclude "README.md" \
            --delete
